apiVersion: v2
name: datahub-prerequisites
description: A Helm chart for packages that Datahub depends on
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.4
dependencies:
  - name: postgresql
    version: 11.2.6
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
  # This chart deploys an enterprise version of kafka that requires commercial license
  # Note, Schema registry and kafka rest proxy do not require the commercial license
  - name: cp-helm-charts
    version: 0.6.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: cp-helm-charts.enabled
  # This chart deploys a community version of kafka
  - name: kafka
    version: 22.1.6
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: kafka.enabled
maintainers:
  - name: DataHub
    email: datahub@acryl.io
